### ISSUE TITLE
demo增强

### ISSUE THREAD

**Issue by Measy** [kenberkeley/msg-board-api#1]
博主您的demo直接用自己写的文件读取系统进行存储；以及鉴权做的也很简单，期待您有空的时候能够升级下这个demo，在安全和性能上稍微提高下。

**Comment by kenberkeley** [comment]
目前 [vue-demo](https://github.com/kenberkeley/vue-demo) 已经不再使用该项目提供后端服务，见 [vue-demo/mock](https://github.com/kenberkeley/vue-demo/tree/master/mock)
