### ISSUE TITLE
router组件中无法读取 req.cookies属性

### ISSUE THREAD

**Issue by Measy** [kenberkeley/msg-board-api#2]
如果在路由中打印
//GET /user
exports.get = function (req, res, next) {
    console.log("========" + req.cookies)
    res.json(userService.isLogin());
}
会出现如下错误，是否req参数不是express中对应的req参数？
TypeError: Cannot convert object to primitive value
    at exports.get (G:\userfulTools\msg-board-server\controllers\user\index.js:5:28)

**Comment by kenberkeley** [comment]
其实这只是 console.log 的限制而已，并不是 `req` 自身的问题

**Comment by Measy** [comment]
哦哦  我看错误信息也像console自身的问题，无法转换类型；可是我自己在app.js中进行打印是可以打印出来的 所以觉得两处的req可能是不一样的。
app.use(function(req, res, next){
  console.log(req.cookies);
  next();
})
在app.js中添加这个是可以打印出cookies的
